[target.mips-unknown-linux-musl]
linker = "/usr/local/musl/bin/mips-unknown-linux-musl-gcc"
rustflags = ["-Ctarget-cpu=mips32r2", "-Ctarget-feature=+soft-float", "-Cllvm-args=--float-abi=soft", "-Clink-arg=-msoft-float", "-Clink-arg=-Wl,--no-warn-mismatch"]
